"""Add ShipmentHistory table

Revision ID: 003e6b8acef1
Revises: d11cf3153dc1
Create Date: 2025-05-20 10:57:23.703206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003e6b8acef1'
down_revision = 'd11cf3153dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('shipment_location', sa.String(length=255), nullable=True),
    sa.Column('shipment_site', sa.String(length=255), nullable=True),
    sa.Column('shipment_start_date', sa.Date(), nullable=True),
    sa.Column('shipment_end_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['construction_machine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment_history')
    # ### end Alembic commands ###
