"""Add used_stock column to Part model

Revision ID: 2508e19a388a
Revises: b323274367f4
Create Date: 2025-05-21 17:05:31.402885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2508e19a388a'
down_revision = 'b323274367f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('part_shipment_history')
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_stock', sa.Integer(), nullable=True))
        batch_op.drop_column('used_available')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_available', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('used_stock')

    op.create_table('part_shipment_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('part_id', sa.INTEGER(), nullable=False),
    sa.Column('shipment_location', sa.VARCHAR(length=120), nullable=True),
    sa.Column('shipment_site', sa.VARCHAR(length=120), nullable=True),
    sa.Column('shipment_start_date', sa.DATE(), nullable=True),
    sa.Column('shipment_end_date', sa.DATE(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
