"""Fix foreign key to surveying_tools

Revision ID: 42494ba1234a
Revises: f8a44a6e7527
Create Date: 2025-05-20 15:04:54.325725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42494ba1234a'
down_revision = 'f8a44a6e7527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveying_shipment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('shipment_location', sa.String(length=100), nullable=True),
    sa.Column('shipment_site', sa.String(length=100), nullable=True),
    sa.Column('shipment_start_date', sa.Date(), nullable=True),
    sa.Column('shipment_end_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tool_id'], ['surveying_tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surveying_shipment_history')
    # ### end Alembic commands ###
