"""Add shipment_site to ConstructionMachine

Revision ID: 445b186cb22a
Revises: 4c1aa8073f48
Create Date: 2025-05-14 17:10:35.690284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445b186cb22a'
down_revision = '4c1aa8073f48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('construction_machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipment_site', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('construction_machine', schema=None) as batch_op:
        batch_op.drop_column('shipment_site')

    # ### end Alembic commands ###
