"""Add shipment_location to ConstructionMachine model

Revision ID: 4c1aa8073f48
Revises: 
Create Date: 2025-05-14 14:11:11.521417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c1aa8073f48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('construction_machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipment_location', sa.String(length=100), nullable=True))
        batch_op.alter_column('serial_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('construction_machine', schema=None) as batch_op:
        batch_op.alter_column('serial_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('shipment_location')

    # ### end Alembic commands ###
