"""Add shipment_site to ConstructionMachine

Revision ID: 5de9a83e0cdd
Revises: 445b186cb22a
Create Date: 2025-05-14 17:19:53.926924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5de9a83e0cdd'
down_revision = '445b186cb22a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('construction_machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipment_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('shipment_end_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('construction_machine', schema=None) as batch_op:
        batch_op.drop_column('shipment_end_date')
        batch_op.drop_column('shipment_start_date')

    # ### end Alembic commands ###
