"""Your message

Revision ID: 742d6e79a661
Revises: 40525eae9299
Create Date: 2025-05-20 10:09:39.735433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742d6e79a661'
down_revision = '40525eae9299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('construction_machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))
        batch_op.drop_column('is_active')

    with op.batch_alter_table('surveying_tools', schema=None) as batch_op:
        batch_op.alter_column('tool_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveying_tools', schema=None) as batch_op:
        batch_op.alter_column('tool_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('construction_machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('state')

    # ### end Alembic commands ###
