"""Add SystemTool model

Revision ID: 76043f57210b
Revises: 42494ba1234a
Create Date: 2025-05-20 16:53:36.302058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76043f57210b'
down_revision = '42494ba1234a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_type', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('shipment_location', sa.String(length=255), nullable=True),
    sa.Column('shipment_site', sa.String(length=255), nullable=True),
    sa.Column('shipment_start_date', sa.Date(), nullable=True),
    sa.Column('shipment_end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_tools')
    # ### end Alembic commands ###
