"""Add SystemShipmentHistory model

Revision ID: 7f99045d87b1
Revises: 76043f57210b
Create Date: 2025-05-21 14:58:58.372355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f99045d87b1'
down_revision = '76043f57210b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_shipment_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_id', sa.Integer(), nullable=False))
        batch_op.alter_column('shipment_location',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('shipment_site',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        #batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_system_shipment_history_system_id', 'system_tools', ['system_id'], ['id'])
        batch_op.drop_column('tool_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_shipment_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tool_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'system_tools', ['tool_id'], ['id'])
        batch_op.alter_column('shipment_site',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('shipment_location',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('system_id')

    # ### end Alembic commands ###
