"""empty message

Revision ID: b323274367f4
Revises: 7f99045d87b1
Create Date: 2025-05-21 16:02:40.273267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b323274367f4'
down_revision = '7f99045d87b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.add_column(sa.Column('part_type', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('part', schema=None) as batch_op:
        batch_op.drop_column('part_type')

    # ### end Alembic commands ###
