"""Add pdf_filename to surveying_tools

Revision ID: d3e453f6cc11
Revises: f809175d31ee
Create Date: 2025-06-03 16:48:24.120931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e453f6cc11'
down_revision = 'f809175d31ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveying_tools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveying_tools', schema=None) as batch_op:
        batch_op.drop_column('pdf_filename')

    # ### end Alembic commands ###
