"""Add updated_at column to SurveyingTool

Revision ID: f809175d31ee
Revises: 2508e19a388a
Create Date: 2025-06-03 16:16:17.333832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f809175d31ee'
down_revision = '2508e19a388a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('construction_machine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('surveying_tools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('system_tools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_tools', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('surveying_tools', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('construction_machine', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
